### ISSUE TITLE
All models require Matterhorn::Inclusions::InclusionSupport

### ISSUE THREAD

**Issue by blasterpal** [blakechambers/matterhorn#33]
Is this a firm requirement as part of Gem or should we make the gem a little smarter. Presently, nested resources throw an exception when `Matterhorn::Inclusions::InclusionSupport` is excluded. 

```
1) multi ids resources with_request "GET /#{collection_name}/:id1,:id4/:nested_collection.json" should use multi-ids to scope relationship
     Failure/Error: perform_request!
     NoMethodError:
       undefined method `__inclusion_configs' for #<Mongoid::Criteria:0x007fc328166668>
     # ./lib/matterhorn/serialization/scoped.rb:68:in `merge_inclusions!'
     # ./lib/matterhorn/serialization/scoped.rb:43:in `block in serializable_hash'
     # ./lib/matterhorn/serialization/scoped.rb:42:in `tap'
     # ./lib/matterhorn/serialization/scoped.rb:42:in `serializable_hash'
     # ./lib/matterhorn/serialization/scoped_collection_serializer.rb:9:in `serializable_hash'
     # ./lib/matterhorn/serialization/scoped.rb:48:in `as_json'
     # ./lib/matterhorn/responder.rb:12:in `default_render'
     # ./lib/matterhorn/resources.rb:111:in `block in index'
     # ./lib/matterhorn/resources.rb:213:in `with_scope'
     # ./lib/matterhorn/resources.rb:110:in `index'
     # ./spec/resources_api/multi_id_resources_spec.rb:83:in `block (3 levels) in <top (required)>'
```

**Comment by blakechambers** [comment]
As methioned [here](https://github.com/blakechambers/matterhorn/issues/42#issuecomment-90128125), I'd like to save any discussions about syntax changes until after the 0.1.0 issues are closed.
